### ISSUE TITLE
"Sorry, unable to open the file at this time"

### ISSUE THREAD

**Issue by ianeverdell** [pfelipm/autoslides#3]
Hi,

I'm trying to display my first project with AutoSlides and when I use the URL provided, Google tells me that it is "unable to open the file at this time."

I'm not sure if I've missed something in the settings (using Google translate, so maybe something has been missed), or how I can fix this.

Thanks!
Ian

**Comment by ianeverdell** [comment]
These are the script deployment settings:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/25497748/179017492-48bb24f4-7df5-4563-a0fc-02289eb347d2.png">

**Comment by pfelipm** [comment]
Hey, AutoSlides should not be returning a link like that for the built-in webapp, but I am aware that there have been some changes to the way things work on Google's side regarding that. Besides that, as you may have already noticed, the Google Slides interface is no longer being correctly hidden on the embed (more changes!), so I guess that I need to do some rework on AutoSlides, that has not been updated for many months. Thanks for reporting this.

**Comment by pfelipm** [comment]
Well, the problem affecting the URL seems to be an ongoing Google issue :-(, hope this is solved soon: https://issuetracker.google.com/issues/235862472
